# Generated by Django 4.2.5 on 2023-10-03 02:52

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', markdownx.models.MarkdownxField(verbose_name='text')),
            ],
        ),
        migrations.CreateModel(
            name='StatisticsBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.CharField(max_length=64, verbose_name='Chapter')),
                ('section', models.CharField(max_length=64, verbose_name='Section')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
