# Generated by Django 4.2.5 on 2023-10-03 04:26

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsBlogs', '0002_post_created_at_post_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsblog',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
