# Generated by Django 4.2.6 on 2023-10-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsBlogs', '0004_delete_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsblog',
            name='text',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
