# Generated by Django 4.2.6 on 2023-11-02 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statisticsBlogs', '0006_alter_statisticsblog_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statisticsblog',
            old_name='text',
            new_name='markdown',
        ),
        migrations.AddField(
            model_name='statisticsblog',
            name='author',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='statisticsblog',
            name='category',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Category'),
        ),
    ]
