# Generated by Django 4.2.6 on 2023-10-24 06:29

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('travelBlogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelblog',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True, default='', null=True, verbose_name='Text'),
        ),
    ]
